-- Create table for ticket email records
-- This table stores tickets generated by organizers and sent to users via email
CREATE TABLE IF NOT EXISTS ticket_emails (
  id SERIAL PRIMARY KEY,
  event_id INTEGER NOT NULL,
  recipient_email VARCHAR(255) NOT NULL,
  ticket_id VARCHAR(255) NOT NULL UNIQUE,
  unique_hash TEXT,
  qr_data TEXT,
  status VARCHAR(50) DEFAULT 'sent',
  badge_sent BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- If table already exists, add badge_sent column:
-- ALTER TABLE ticket_emails ADD COLUMN IF NOT EXISTS badge_sent BOOLEAN DEFAULT FALSE;

-- Create indexes for faster lookups
CREATE INDEX IF NOT EXISTS idx_ticket_emails_recipient ON ticket_emails(recipient_email);
CREATE INDEX IF NOT EXISTS idx_ticket_emails_event ON ticket_emails(event_id);
CREATE INDEX IF NOT EXISTS idx_ticket_emails_ticket_id ON ticket_emails(ticket_id);

-- Add comment to table
COMMENT ON TABLE ticket_emails IS 'Stores records of tickets sent to email addresses';
