-- Create table for ticket email records
-- This table stores tickets generated by organizers and sent to users via email
CREATE TABLE IF NOT EXISTS ticket_emails (
  id SERIAL PRIMARY KEY,
  event_id INTEGER NOT NULL,
  recipient_email VARCHAR(255) NOT NULL,
  ticket_id VARCHAR(255) NOT NULL UNIQUE,
  unique_hash TEXT,
  qr_data TEXT,
  status VARCHAR(50) DEFAULT 'sent',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create index for faster lookups
CREATE INDEX IF NOT EXISTS idx_ticket_emails_recipient ON ticket_emails(recipient_email);
CREATE INDEX IF NOT EXISTS idx_ticket_emails_event ON ticket_emails(event_id);
CREATE INDEX IF NOT EXISTS idx_ticket_emails_ticket_id ON ticket_emails(ticket_id);

-- Create index on ticket_id for faster queries
CREATE INDEX idx_ticket_emails_ticket_id ON ticket_emails(ticket_id);

-- Create index on recipient_email for faster queries
CREATE INDEX idx_ticket_emails_recipient_email ON ticket_emails(recipient_email);

-- Create index on event_id for faster queries
CREATE INDEX idx_ticket_emails_event_id ON ticket_emails(event_id);

-- Add comment to table
COMMENT ON TABLE ticket_emails IS 'Stores records of tickets sent to email addresses';
